use crate::features::bda::domain::{
    bda_report::BdaReport,
    report_template::{GenerateReportRequest, ReportClassification},
};
use super::json::generate_json;

pub fn generate_html(
    report: &BdaReport,
    request: &GenerateReportRequest,
) -> Result<String, String> {
    // We still use generate_json internally if needed, or just format direct
    // The original code used generate_json just to get json_data but didn't actually use it in the HTML format!
    // It used `request` and `report` directly in `format!`.
    // I will keep the call to strictly match original logic or remove it if unused.
    // Looking at original code: `let json_data = Self::generate_json(report, request)?;`
    // usage of json_data: NONE.
    // So I can remove the dependency if I want, but for safety I'll keep it or verify.
    // Actually, `generate_json` might do some validation? No.
    // I will omit the call to `generate_json` as it was unused in the HTML generation logic.
    
    let classification = request.classification
        .unwrap_or(ReportClassification::Secret);
    
    let html = format!(r#"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>BDA Report - {}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            background: #1e1e1e;
            color: #e0e0e0;
        }}
        .header {{
            border-bottom: 2px solid #444;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .classification {{
            background: #8b0000;
            color: white;
            padding: 10px;
            text-align: center;
            font-weight: bold;
            margin-bottom: 20px;
        }}
        .section {{
            margin-bottom: 30px;
        }}
        .section-title {{
            font-size: 18px;
            font-weight: bold;
            color: #4a9eff;
            margin-bottom: 10px;
            border-bottom: 1px solid #444;
            padding-bottom: 5px;
        }}
        .field {{
            margin-bottom: 10px;
        }}
        .field-label {{
            font-weight: bold;
            color: #aaa;
            margin-right: 10px;
        }}
        .field-value {{
            color: #e0e0e0;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #444;
            text-align: center;
            color: #888;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="classification">{}</div>
    
    <div class="header">
        <h1>BDA Report - {}</h1>
        <p>Report ID: {}</p>
        <p>Generated: {}</p>
    </div>
    
    <div class="section">
        <div class="section-title">Physical Damage Assessment</div>
        <div class="field">
            <span class="field-label">Category:</span>
            <span class="field-value">{}</span>
        </div>
        <div class="field">
            <span class="field-label">Percentage:</span>
            <span class="field-value">{}</span>
        </div>
        <div class="field">
            <span class="field-label">Description:</span>
            <span class="field-value">{}</span>
        </div>
    </div>
    
    <div class="section">
        <div class="section-title">Functional Damage Assessment</div>
        <div class="field">
            <span class="field-label">Status:</span>
            <span class="field-value">{}</span>
        </div>
        <div class="field">
            <span class="field-label">Repair Time:</span>
            <span class="field-value">{} hours</span>
        </div>
    </div>
    
    <div class="section">
        <div class="section-title">Effects Assessment</div>
        <div class="field">
            <span class="field-label">Desired Effect:</span>
            <span class="field-value">{}</span>
        </div>
        <div class="field">
            <span class="field-label">Achieved Effect:</span>
            <span class="field-value">{}</span>
        </div>
    </div>
    
    <div class="section">
        <div class="section-title">Recommendation</div>
        <div class="field">
            <span class="field-label">Type:</span>
            <span class="field-value">{}</span>
        </div>
        <div class="field">
            <span class="field-label">Re-Attack Priority:</span>
            <span class="field-value">{}</span>
        </div>
    </div>
    
    <div class="footer">
        <p>Classification: {} | Generated by BDA Workbench</p>
    </div>
</body>
</html>
"#,
        request.template_type.display_name(),
        classification.banner(),
        request.template_type.display_name(),
        report.id,
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
        format!("{:?}", report.physical_damage),
        report.physical_damage_percentage.map(|p| p.to_string()).unwrap_or_else(|| "N/A".to_string()),
        report.damage_description.as_deref().unwrap_or("N/A"),
        format!("{:?}", report.functional_damage),
        report.estimated_repair_time_hours.map(|h| h.to_string()).unwrap_or_else(|| "N/A".to_string()),
        report.desired_effect,
        report.achieved_effect,
        format!("{:?}", report.recommendation),
        report.re_attack_priority.map(|p| p.to_string()).unwrap_or_else(|| "N/A".to_string()),
        classification.marking(),
    );
    
    Ok(html)
}
